language: node_js

serivces:
  - docker

env:
  - TRAVIS_BUILD_DIR

before_install:
  - cd Server
  - npm run docker:build
  - echo "$DOCKER_PASSWORD" | docker login relang.azurecr.io -u "$DOCKER_USERNAME" --password-stdin
  - npm run docker:push

install:
  - echo ----------- do not run npm install ------------
